### ISSUE TITLE
Broken Link:  Component living documentation

### ISSUE THREAD

**Issue by thekingofspain** [OutSystems/outsystems-datagrid#311]
[README.md](https://github.com/OutSystems/outsystems-datagrid#readme)

[Useful Links] (https://github.com/OutSystems/outsystems-datagrid#useful-links

Component [living documentation](https://personal-ww5hcsw8.outsystemscloud.com/DataGridSampleReactive/)

**Comment by gnbm** [comment]
Thank you for reaching out @thekingofspain 
The link is already fixed. Cheers!
